module "okta_idp_saml" {
  source = "./modules/okta/r/okta_idp_saml"

  account_link_action          = null
  account_link_group_include   = []
  acs_binding                  = null
  acs_type                     = null
  deprovisioned_action         = null
  groups_action                = null
  groups_assignment            = []
  groups_attribute             = null
  groups_filter                = []
  issuer                       = null
  issuer_mode                  = null
  kid                          = null
  name                         = null
  name_format                  = null
  profile_master               = null
  provisioning_action          = null
  request_signature_algorithm  = null
  request_signature_scope      = null
  response_signature_algorithm = null
  response_signature_scope     = null
  sso_binding                  = null
  sso_destination              = null
  sso_url                      = null
  status                       = null
  subject_filter               = null
  subject_format               = []
  subject_match_attribute      = null
  subject_match_type           = null
  suspended_action             = null
  username_template            = null
}
